# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# How is the pipeline getting triggered - 
# manually(when we click on run pipeline) or 
# automatically(when a change in the github code would trigger the pipeline)
trigger: # when do u want to run the pipeline
- main

pool: # the agent running the CI/CD pipeline. where do u want to run the pipeline
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world, changed!
  displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo add more tasks
      displayName: 'Run a multi-line script'
 - job: job2
   dependsOn: job1  
   steps:
      - script: echo job2
        displayName: 'Run a one line script'
 - job: job3
   dependsOn: job2
   steps:
     - script: echo job3
       displayName: 'Run a one-line script'    


# In Azure, an agent typically refers to software or a service that performs tasks on behalf of users or other 
# software components within the Azure ecosystem. These agents can perform a variety of functions, such as 
# monitoring, data collection, automation, or management tasks.

# For example, in Azure DevOps, there are deployment agents that execute deployment tasks on target machines,
# allowing continuous integration and continuous deployment (CI/CD) pipelines to automate software delivery 
#processes.